// examples/react/src/routes/signin.tsx
import type { AriaAttributes, FormEventHandler } from 'react'
import type { authApiSchema } from '@/api/schemas/auth-schema'
import { createFileRoute, Link, useNavigate } from '@tanstack/react-router'
import { isValidationError } from 'mock-dash'
import { useState } from 'react'
import z from 'zod'
import { apiClient } from '@/api/api-client'
import { CenterLayout } from '@/components/center-layout/center-layout'
import { ErrorParagraph } from '@/components/error-paragraph/error-paragraph'

export const Route = createFileRoute('/signin')({
  component: RouteComponent,
  validateSearch: z.object({
    redirect: z.string(),
  }),
})

type JSON = typeof authApiSchema.$inferInputJson['@post/auth/sign-in/email']

function RouteComponent() {
  const navigate = useNavigate()
  const { redirect } = Route.useSearch()

  const [errors, setErrors] = useState<ReturnType<typeof z.treeifyError<JSON>>>({
    errors: [],
    properties: {},
  })

  const handleSubmit: FormEventHandler<HTMLFormElement> = async (
    event,
  ) => {
    setErrors({ errors: [], properties: {} })

    event.preventDefault()
    const formData = new FormData(event.currentTarget, (event.nativeEvent as SubmitEvent).submitter)
    const data: JSON = {
      email: formData.get('email') as string,
      password: formData.get('password') as string,
      rememberMe: formData.get('remember') !== undefined,
    }

    try {
      await apiClient('@post/auth/sign-in/email', { json: data })

      navigate({
        to: redirect,
      })
    }
    catch (error) {
      if (isValidationError(error)) {
        setErrors(z.treeifyError(error.validationErrors as z.ZodError<JSON>))
      }
      else {
        setErrors({
          errors: ['Could not signin'],
          properties: {},
        })
      }
    }
  }

  function addFieldErrors(key: keyof JSON) {
    const err = errors.properties?.[key]
    if (err) {
      return {
        'aria-invalid': 'true',
        'aria-describedby': `${key}-helper`,
      } satisfies AriaAttributes
    }

    return {}
  }

  return (
    <CenterLayout>
      <article>
        <header>Signin</header>
        <form onSubmit={handleSubmit}>
          <label>
            Email
            <input
              placeholder="Email"
              aria-label="Email"
              autoComplete="email"
              required
              type="text"
              name="email"
              {...addFieldErrors('email')}
            />
            {(errors.properties?.email?.errors ?? []).map(error => (
              <small id="email-helper">{error}</small>
            ))}

          </label>
          <label>
            Password
            <input
              placeholder="Password"
              aria-label="Password"
              autoComplete="current-password"
              required
              type="password"
              name="password"
              {...addFieldErrors('password')}

            />
            {(errors.properties?.password?.errors ?? []).map(error => (
              <small id="password-helper">{error}</small>
            ))}
          </label>
          <fieldset>
            <label htmlFor="remember">
              <input
                role="switch"
                id="remember"
                type="checkbox"
                name="remember"
              />
              Remember me
            </label
            >
          </fieldset>
          <button type="submit">Signin</button>

          {(errors.errors).map(error => (
            <ErrorParagraph>{error}</ErrorParagraph>
          ))}
          <small>
            Don't have an account?
            <Link to="/signup" search={{ redirect }}>signup</Link>
          </small>
        </form>
      </article>
    </CenterLayout>
  )
}

// examples/sveltekit/src/routes/(auth)/signin/+page.svelte
<script lang='ts'>
  import type { authApiSchema } from '$lib/schemas/auth-schema'
  import type { AriaAttributes } from 'svelte/elements'
  import type { PageProps } from './$types'
  import { goto } from '$app/navigation'
  import { apiClient } from '$lib/api-client'
  import CenterLayout from '$lib/components/CenterLayout.svelte'
  import ErrorParagraph from '$lib/components/ErrorParagraph.svelte'
  import { isValidationError } from 'mock-dash'
  import z from 'zod'

  const { data }: PageProps = $props()
  const { redirect } = data

  type JSON = (typeof authApiSchema.$inferInputJson['@post/auth/sign-in/email'])

  let errors = $state<ReturnType<typeof z.treeifyError<JSON>>>({
    errors: [],
    properties: {},
  })

  async function handleSubmit(
    event: SubmitEvent & { currentTarget: EventTarget & HTMLFormElement },
  ) {
    errors = { errors: [], properties: {} }
    event.preventDefault()
    const formData = new FormData(event.currentTarget, event.submitter)
    const data: JSON = {
      email: formData.get('email') as string,
      password: formData.get('password') as string,
      rememberMe: formData.get('remember') !== undefined,
    }

    try {
      await apiClient('@post/auth/sign-in/email', { json: data })

      goto(redirect)
    }
    catch (error) {
      if (isValidationError(error)) {
        errors = z.treeifyError(error.validationErrors as z.ZodError<JSON>)
      }
      else {
        errors = {
          errors: ['Could not signin'],
          properties: {},
        }
      }
    }
  }

  function addFieldErrors(key: keyof JSON) {
    const err = errors.properties?.[key]
    if (err) {
      return {
        'aria-invalid': 'true',
        'aria-describedby': `${key}-helper`,
      } satisfies AriaAttributes
    }

    return {}
  }
</script>

<svelte:head>
  <title>Sign up</title>
</svelte:head>

<CenterLayout>
  <article>
    <header>Signup</header>
    <form onsubmit={handleSubmit}>
      <label>
        Email
        <input
          placeholder='Email'
          aria-label='Email'
          autocomplete='email'
          required
          type='text'
          name='email'
          {...addFieldErrors('email')}
        />
        {#each errors.properties?.email?.errors ?? [] as error}
          <small id='email-helper'>{error}</small>
        {/each}
      </label>
      <label>
        Password
        <input
          placeholder='Password'
          aria-label='Password'
          autocomplete='current-password'
          required
          type='password'
          name='password'
          {...addFieldErrors('password')}

        />
        {#each errors.properties?.password?.errors ?? [] as error}
          <small id='password-helper'>{error}</small>
        {/each}
      </label>
      <fieldset>
        <label for='remember'>
          <input
            role='switch'
            id='remember'
            type='checkbox'
            name='remember'
          />Remember me</label
        >
      </fieldset>
      <button type='submit'>Signin</button>
      {#each errors.errors as error}
        <ErrorParagraph msg={error} />
      {/each}
      <small>Don't have an account? <a href='/signup'>signup</a></small>
    </form>
  </article>
</CenterLayout>
